### ISSUE TITLE
Implement HTTPS

### ISSUE THREAD

**Issue by InnovativeInventor** [mpcovcd/spyfall#56]
If possible, Spyfall should be available over https for SEO reasons (Google is giving a slight incentive for implementing https) and because implementing https will help encourage others to do the same

**Comment by InnovativeInventor** [comment]
Just an update - on July, Google Chrome will shame sites still using http ([source](https://techcrunch.com/2018/02/08/chrome-will-soon-mark-all-unencrypted-pages-as-not-secure/)). A few easy methods to switch to https include using Cloudflare's SSL proxy (its free) or something like this [zodern/meteor-up](https://github.com/zodern/meteor-up).

**Comment by mpcovcd** [comment]
HTTPs has been implemented!
