### ISSUE TITLE
New Maintainer(s)

### ISSUE THREAD

**Issue by ryanneph** [mpcovcd/spyfall#66]
I've seen that a number of devs have forked this repo with an interest in contributing either casually or as long-term maintainers, myself as a recent addition. I'm wondering if we should take the official steps of passing or adding ownership of the original repo to a small group of us who would be willing to maintain for the near future.

The current owner of the repo @mpcovcd hasn't been active since September of last year and the most recent (forked) commits are from @dohlin and @scooter3. I'm wondering if you would like to be official co-contributors with me so we can continue to improve this project? 

I've observed that the personalities at https://www.youtube.com/user/Node/ have been playing spyfall from their phones for a few years, switching back and forth between this implementation and @adrianocola's, and have had stability issues with both over time. There are aspects of each codebase that are strong, perhaps we could converge the two instances if there is enough support to do so. 

Any interest in making this more official?

**Comment by mpcovcd** [comment]
I am very well active. If you are interested in maintaining the repo or pushing commits I would be happy to review. I appreciate all of the help @dohlin and @scooter3 have contributed to the repo and making this game wonderful for all of it's users. The stability issues were due to server load, and most have been resolved after beefing up the server which occurred about two months ago. Would be open to hear ideas on how to improve stability.

**Comment by dohlin** [comment]
I know absolutely nothing about coding and barely know my way around GitHub, lol, otherwise I'd definitely consider it.  Sorry!

**Comment by ryanneph** [comment]
Ok wonderful, I hope I didn’t offend anyone. I’ll open some issues here in the future with my suggestions. I don’t see any reason to change ownership knowing that @mpcovcd is active. Thanks for maintaining the project!

**Comment by InnovativeInventor** [comment]
Maybe using something like AWS Lambda or AWS Elastic Beanstalk (doesn't have to be AWS, I'm just listing these because I'm somewhat familiar with them) would help with scaling.

**Comment by hurrikan1** [comment]
@mpcovcd Are you trying to solve server stability issues before accepting the pull requests? I'm definitely interested in being involved in this project and being a regular contributor if that's something you're looking for.
